### ISSUE TITLE
Run by nodejs

### ISSUE THREAD

**Issue by asedali** [Eligioo/nimiq-pool-webminer#1]
Can I run this script local by node js?
Run without browser?

**Comment by Eligioo** [comment]
I don't see a reason why you would use a webminer in Nodejs. If you want to start mining Nimiq, you can use one of the miner clients like this one: https://github.com/Beeppool/miner

**Comment by asedali** [comment]
Thanks for your reply.
I have a node js host and can not install compiled package.
I need a node js app that can mine.

**Comment by Eligioo** [comment]
For CPU mining I recommend https://github.com/Beeppool/miner. It was originally made for Beeppool only but you can use it to mine on other pools as well.
For GPU mining I recommend https://github.com/tomkha/nq-miner. 

In general it has a better performance than the node js app.
